### ISSUE TITLE
Error exporting subworkflow

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/gxformat2#31]
When exporting the big all-in-one subworkflow that includes the 2 variants for single-end and paired-end workflows the export fails with
```
galaxy.web.framework.decorators ERROR 2020-06-01 18:04:18,839 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/decorators.py", line 295, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 471, in workflow_dict
    ret_dict = self.workflow_contents_manager.workflow_to_dict(trans, stored_workflow, style=style, version=version)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/workflows.py", line 480, in workflow_to_dict
    wf_dict = to_format_2(wf_dict)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/workflows.py", line 461, in to_format_2
    return from_galaxy_native(wf_dict, None, **kwds)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/gxformat2/export.py", line 54, in from_galaxy_native
    output_id = labels.ensure_new_output_label(workflow_output.get("label"))
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/gxformat2/_labels.py", line 17, in ensure_new_output_label
    assert label not in self.seen_labels
AssertionError
```

I think `assert label not in self.seen_labels` might need to be scoped to individual workflows ?

**Comment by mvdbeek** [comment]
This is the .ga in question: https://gist.github.com/mvdbeek/7d6c1da73e54b12f0163c0440b786161

just tracking it here so I don't forget.

**Comment by mvdbeek** [comment]
I'm not sure what to do here ... if we want to switch to export gxformat2 by default we should be able to export all existing workflows IMO, but if we auto-fix or drop the redundant labels we can't go back to the native format without losing the labels. As a sidenote, you can't produce a workflows like this anymore because of https://github.com/galaxyproject/galaxy/pull/10432 and the editor will try to "fix" this for you by dropping the redundant labels ... which I guess is an option ?

**Comment by nsoranzo** [comment]
> As a sidenote, you can't produce workflows like this anymore because of [galaxyproject/galaxy#10432](https://github.com/galaxyproject/galaxy/pull/10432) and the editor will try to "fix" this for you by dropping the redundant labels ... which I guess is an option ?

I agree that dropping the redundant labels is a good option, since that's also what happens if you try to import into UseGalaxy.org the .ga file you linked above.

**Comment by mvdbeek** [comment]
Try uploading the workflow, then downloading it. The redundant label is still there. If we silently dropped the label on import that would be really really bad, but that's not happening. The editor will warn you about the duplicate label and then drop it, you need to save for the label to disappear.

I think we've decided we'd fall back to the `.ga` download when we can't produce .gxformat2 because of this issue.
